### ISSUE TITLE
Unable to install amber with homebrew crystal 0.30.0

### ISSUE THREAD

**Issue by libjade** [amberframework/homebrew-amber#4]
`==> Installing amber from amberframework/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.29.0.tar.gz
Already downloaded: /Users/mario/Library/Caches/Homebrew/downloads/c151cf73407c70c06314c49139d67fa0b85210153319b7e8bdf0c402e97a620a--amber-0.29.0.tar.gz
==> shards install
==> make install PREFIX=/usr/local/Cellar/amber/0.29.0
Last 15 lines from /Users/mario/Library/Logs/Homebrew/amber/02.make:
2019-08-04 14:30:33 +0200

make
install
PREFIX=/usr/local/Cellar/amber/0.29.0

Building amber in bin/amber
Showing last frame. Use --error-trace for full trace.

In /usr/local/Cellar/crystal/0.30.0/src/enumerable.cr:37:16

 37 | abstract def each(&block : T -> _)
                   ^---
Error: abstract `def Enumerable(T)#each(&block)` must be implemented by Callback::ResultSet(T)
make: *** [bin/amber] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/amberframework/homebrew-amber/issues`

**Comment by zekitow** [comment]
I'm getting the same error as well

**Comment by drujensen** [comment]
Waiting on several dependencies before we can upgrade amber to use crystal 0.30.0.  You can use crystal 0.29.0 for now.

https://github.com/amberframework/amber/issues/1125

**Comment by zekitow** [comment]
@drujensen I've tried again today and now it worked! Maybe you can close this issue.
