### ISSUE TITLE
can't install amber 0.30.0 

### ISSUE THREAD

**Issue by ostholz** [amberframework/homebrew-amber#5]
~ brew install amber
==> Installing amber from amberframework/amber
==> Downloading https://github.com/amberframework/amber/archive/v0.30.0.tar.gz
Already downloaded: /Users/dong/Library/Caches/Homebrew/downloads/def43830a3c2e00740d189a33fa3ed30131c4a8c2b0eeccd2a4f3ae8a174ea73--amber-0.30.0.tar.gz
==> shards install
Last 15 lines from /Users/dong/Library/Logs/Homebrew/amber/01.shards:
2019-08-08 22:10:36 +0200

shards
install

dyld: Library not loaded: /usr/local/opt/libevent/lib/libevent-2.1.6.dylib
  Referenced from: /usr/local/opt/crystal/bin/shards
  Reason: image not found

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/amberframework/homebrew-amber/issues

These open issues may also help:
Unable to install amber with homebrew crystal 0.30.0 https://github.com/amberframework/homebrew-amber/issues/4

brew install libevent@2.1.6 also no luck

**Comment by drujensen** [comment]
Can you try `brew update;brew upgrade`

**Comment by drujensen** [comment]
yeah, that doesn't seem right.

What do you get when you run `brew info libevent`?

Here is what i'm getting:
```
$brew info libevent
libevent: stable 2.1.11 (bottled)
Asynchronous event library
https://libevent.org/
Conflicts with:
  pincaster (because both install `event_rpcgen.py` binaries)
/usr/local/Cellar/libevent/2.1.11 (1,063 files, 5MB) *
  Poured from bottle on 2019-08-07 at 23:19:39
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libevent.rb
==> Dependencies
Build: autoconf ✔, automake ✔, doxygen ✔, libtool ✔, pkg-config ✔
Required: openssl ✔
==> Analytics
install: 189,916 (30 days), 571,213 (90 days), 1,218,549 (365 days)
install_on_request: 6,137 (30 days), 17,467 (90 days), 34,379 (365 days)
build_error: 0 (30 days)
```

**Comment by ostholz** [comment]
I did not run this. I've tried to install 2.1.6, but with error.

brew install libevent@2.1.6
Error: No available formula with the name "libevent@2.1.6" 
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.

**Comment by drujensen** [comment]
~try `brew install libevent`~

nm, you have `libevent 2.1.7` installed which is the same as what I have.  

I'm stumped. Maybe try `brew remove crystal && brew remove amber` and then re-install?

**Comment by lukeholder** [comment]
I am also getting `Error resolving db (~> 0.7.0, ~> 0.6.0)`

**Comment by eliasjpr** [comment]
Closing in favor of the new crystal versions
